### ISSUE TITLE
RESTBL editor not saving

### ISSUE THREAD

**Issue by ziahryuk** [NX-Editor/NxEditor.EpdPlugin#11]
Hi! I was using this tool to edit the filesize of a texture in the rstbl, and after hitting "save as" to overwrite the rstbl file in my mod, the tool never finishes saving, it continuously says "saving 'filename....' and after some time still does not actually save. 
Thanks for any help, and apologies if this is too vague/unhelpful im very new to this space.

**Comment by ArchLeaders** [comment]
Can you send the log (`File > Open Logs Folder`, last file in the folder)? It could be a couple things, but whatever it is should be written to the log file.

Could be that the RCL file with the edit is invalid. Or some other vague thing, either way it'll probably say in the log file.

**Comment by ziahryuk** [comment]
I thought to check log but it also wasn't saying anything other than the same saving message

[2023-08-31-02-40.txt](https://github.com/NX-Editor/NxEditor.EpdPlugin/files/12489235/2023-08-31-02-40.txt)

**Comment by ArchLeaders** [comment]
Very true, must be something else wrong.

Can you send the RCL file?

**Comment by ziahryuk** [comment]
[rcl gen.zip](https://github.com/NX-Editor/NxEditor.EpdPlugin/files/12492092/rcl.gen.zip)

**Comment by ArchLeaders** [comment]
Numeric values cannot have commas in them, I'll make sure to handle that better though.
