### ISSUE TITLE
Files being put into .msbt file locations if they are simultaneously opened

### ISSUE THREAD

**Issue by Waikuteru** [NX-Editor/NxEditor.EpdPlugin#12]
Hello,

I edited a language pack USen, and inside a .msbt. Saving worked fine until I opened the RSTB as well in this active NX-Editor instance. When I saved, the language pack went from 2MB to 4MB and I wondered why. I then also opened the GameDataList, made some changes, saved, and also saved the language pack again and it put both the RSTB as well as the GameDataList file into the location in where the .msbt I was editing can be found. I'll attach a screenshot (the 2 files are found at the top and normally don't belong in there): 
![image](https://github.com/NX-Editor/NxEditor/assets/89609865/372fb130-523f-421c-b39d-6bad7df5c7f7)
![image](https://github.com/NX-Editor/NxEditor/assets/89609865/2b312c29-55b3-4853-ba8a-66a1048b732e)

Why is this an issue? The language pack got very big because of that and the game cannot boot with such a big language file anymore.

**Comment by ArchLeaders** [comment]
I couldn't recreate this, do you think you could be more specific about what you were doing?

**Comment by Waikuteru** [comment]
> Sounds like an issue with the sarc sub-file saving logic, I'll look into it when I can.

I opened USen, copied the contents from my Randomizer.msbt from USen, then also dragged EUde onto NX to open it, then also opened Randomizer.msbt, and it defaulted to the Randomizer.msbt tab I had for USen instead of creating a new one.

So currently what I do is usually close NX for every language pack I edit to make sure nothing is cached or a file from another language pack is accidentally edited.

**Comment by ArchLeaders** [comment]
Couldn't find the issue, but I did a lot of work on the IO so this shouldn't be an issue. Feel free to re-open if it's still an issue.
