### ISSUE TITLE
SarcEditor improperly tracks saving

### ISSUE THREAD

**Issue by kianagit** [NX-Editor/NxEditor.EpdPlugin#13]
When opening a .zs-file (in my case any pack.zs files) will end up showing a popup saying "You have unsaved changes" when closing.
The File has definitely been saved, and changes also work 100% ingame, the popup still appears. (Saved the bgyml and the .zs file both separately with ctrl+s)

![image](https://github.com/NX-Editor/NxEditor/assets/80840951/5bf8b8a6-91fd-47c8-8bb1-899916c3e553)
 
Edit: It doesn't break functionality, i can still click "yes", but it's quite weird still.

**Comment by ArchLeaders** [comment]
Could not re-create. The only thing close was I noticed that if you start renaming a node but then exit it will think the file has changed.
