### ISSUE TITLE
Cannot open files without RESTBL strings set up

### ISSUE THREAD

**Issue by MasterBubbles** [NX-Editor/NxEditor.EpdPlugin#14]
Hi Arch!

Here's a bug: it isn't possible to open any file type (such as .pack.zs or .sarc.zs for example) if the RESTBL strings .txt file is not properly setup in the settings, even if the file we try to open has nothing to do with resource tables

**Comment by ArchLeaders** [comment]
Should be fixed in https://github.com/NX-Editor/NxEditor.EpdPlugin/commit/e2c1160d9cf3d02364f980b925d1774037dd1d3b
