### ISSUE TITLE
Batch Import Resource Size Table Edits

### ISSUE THREAD

**Issue by AsteroidPizza39** [NX-Editor/NxEditor.EpdPlugin#3]
The purpose of this feature would be to increase the efficiency of editing the Resource Size Table for the sake of creating mods and increasing version compatibility. Here is how I would imagine this working, with the example file of `ResourceSizeTable.Product.112.rsizetable`. 

1. In nx-editor, open `ResourceSizeTable.Product.112.rsizetable`
2. In the Tools dropdown, there will be an option that reads `Batch Import RSTB Modifications`
3. Clicking that option prompts the user to select a txt file containing the paths and sizes of the modified files (An example of the content structure of this text file is attached)
4. The edits and additions to `ResourceSizeTable.Product.112.rsizetable` are applied automatically

![image](https://github.com/NX-Editor/NxEditor/assets/45804670/4c308b21-fe47-4712-a3b9-9f5ed22ed0dc)
[RSTB Edits.txt](https://github.com/NX-Editor/NxEditor/files/11854145/RSTB.Edits.txt)

**Comment by ArchLeaders** [comment]
> if it would have to communicate between plugins, maybe base it in the main program and have it go through that?

Completely forgot to respond to this.

This works fine, but kind of defeats the point of plugins all together.

**Comment by ArchLeaders** [comment]
Implemented in the new restbl editor
