### ISSUE TITLE
Find & Replace from the menu does not work

### ISSUE THREAD

**Issue by crustySenpai** [NX-Editor/NxEditor.EpdPlugin#4]
So i'm not sure if i do anything wrong but if i try to use Find & Replace under Edit it opens up and i can find words/numbers but i can't replace any of the words/numbers also non of the buttons beside the bars seem to do anything

https://www.youtube.com/watch?v=kufci3-Jw_E

i'm completely new to totk modding and if i'm just dumb or this is a known issue i apologize

**Comment by ArchLeaders** [comment]
From what I can tell this is an issue with using the menu. So for the time being I've disabled it and you can only use `Ctrl+F` and `Ctrl+H` to find/replace.

**Comment by ArchLeaders** [comment]
Something fails with the AvaloniaEdit Find/Replace control when calling Show() from another thread, so until that's fixed a warning is shown to use the hotkeys instead.
